spring.application.name=demo-spring-batch-csv-to-json

# отключает автозапуск job при старте приложения. Мы потом будем запускать её сами
spring.batch.job.enabled=false

# Spring Batch создаст свои служебные таблицы в H2
spring.batch.jdbc.initialize-schema=always

# подключение к H2 in-memory
spring.datasource.url=jdbc:h2:mem:batchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# не обязательно, но полезно.
spring.h2.console.enabled=true